"use client";

import React, { useState, useEffect } from "react";
import { 
  FileCheck,
  Download,
  Check,
  Building2,
  Calendar,
  AlertCircle,
  Loader2,
  ShieldCheck
} from "lucide-react";

export default function MedicalVisaPage() {
  const [isDownloaded, setIsDownloaded] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [travelData, setTravelData] = useState<any>(null);

  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      try {
        const res = await fetch('/api/patient/travel');
        const data = await res.json();
        if (data.success) setTravelData(data);
      } catch (e) {
        console.error('Failed to load visa data', e);
      } finally {
        setIsLoading(false);
      }
    };
    fetchData();
  }, []);

  const activeCase = travelData?.activeCase;

  const handleDownload = () => {
    setIsDownloaded(true);
    const refNo = activeCase?.visaReference || 'PENDING';
    const hospital = activeCase?.hospital?.name || 'Your assigned hospital';
    const doctor = activeCase?.doctor?.name || 'Your assigned physician';
    const content = `GOVERNMENT OF INDIA - EMBASSY VISA INVITATION SUPPORT
Ref No: ${refNo}

This is to certify that the named patient has been accepted for medical treatment
(${activeCase?.treatment || 'Medical Treatment'}) at ${hospital}
under the care of ${doctor}.

Validity: ${activeCase?.visaExpiry || 'As per visa stamp'}
Accreditation: Joint Commission International (JCI) Accredited Hospital.

Generated by MAIDES Medical Tourism Platform.`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `MAIDES-Visa-Letter-${refNo}.txt`;
    a.click();
    setTimeout(() => setIsDownloaded(false), 3000);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="w-6 h-6 text-blue-600 animate-spin mr-2" />
        <span className="text-sm text-slate-500">Loading visa information...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div>
        <h1 className="text-xl font-bold text-slate-900 tracking-tight">
          Medical Visa Assistance
        </h1>
        <p className="text-xs text-slate-500 mt-1">
          Access your official medical visa invitation letter and FRRO registration details.
        </p>
      </div>

      {!activeCase ? (
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-semibold text-amber-800">Visa Letter Not Yet Available</p>
            <p className="text-xs text-amber-600 mt-1">
              Your medical visa invitation letter will be generated once your treatment case has been confirmed and a hospital assigned. Please check back later or contact your coordinator.
            </p>
          </div>
        </div>
      ) : (
        <>
          {/* Status Banner */}
          <div className={`rounded-2xl p-5 flex items-center justify-between gap-4 ${
            activeCase.visaStatus === 'Letter Issued'
              ? 'bg-emerald-50 border border-emerald-200'
              : 'bg-amber-50 border border-amber-200'
          }`}>
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-xl ${activeCase.visaStatus === 'Letter Issued' ? 'bg-emerald-100' : 'bg-amber-100'}`}>
                <ShieldCheck className={`w-5 h-5 ${activeCase.visaStatus === 'Letter Issued' ? 'text-emerald-600' : 'text-amber-600'}`} />
              </div>
              <div>
                <div className="text-sm font-bold text-slate-800">
                  Visa Status: <span className={activeCase.visaStatus === 'Letter Issued' ? 'text-emerald-700' : 'text-amber-700'}>
                    {activeCase.visaStatus || 'Pending'}
                  </span>
                </div>
                <div className="text-xs text-slate-500 mt-0.5">
                  Ref: {activeCase.visaReference || 'Pending generation'}
                </div>
              </div>
            </div>
            {activeCase.visaReference && (
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 text-xs font-bold transition-all shadow-sm shrink-0"
              >
                {isDownloaded ? <Check className="w-4 h-4 text-emerald-600" /> : <Download className="w-4 h-4 text-blue-600" />}
                {isDownloaded ? "Downloaded!" : "Download Visa Letter"}
              </button>
            )}
          </div>

          {/* Visa Details Card */}
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-5">
            <div className="flex items-center gap-3 border-b border-slate-100 pb-4">
              <div className="p-2 rounded-xl bg-blue-50 text-blue-600">
                <FileCheck className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-sm font-bold text-slate-800">Visa Invitation Letter Details</h2>
                <div className="text-xs text-slate-500">Official FRRO Medical Visa Support Document</div>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
              <div className="space-y-1">
                <div className="text-slate-400 uppercase tracking-wider text-[10px] font-bold">Treating Hospital</div>
                <div className="flex items-start gap-1.5 font-semibold text-slate-800">
                  <Building2 className="w-3.5 h-3.5 text-blue-500 mt-0.5 shrink-0" />
                  {activeCase.hospital?.name || 'Pending Assignment'}
                </div>
                {activeCase.hospital?.city && (
                  <div className="text-slate-500 pl-5">{activeCase.hospital.city}</div>
                )}
              </div>

              <div className="space-y-1">
                <div className="text-slate-400 uppercase tracking-wider text-[10px] font-bold">Treating Physician</div>
                <div className="font-semibold text-slate-800">{activeCase.doctor?.name || 'Pending Assignment'}</div>
                {activeCase.doctor?.specialty && (
                  <div className="text-slate-500">{activeCase.doctor.specialty}</div>
                )}
              </div>

              <div className="space-y-1">
                <div className="text-slate-400 uppercase tracking-wider text-[10px] font-bold">Treatment / Procedure</div>
                <div className="font-semibold text-slate-800">{activeCase.treatment || 'Pending'}</div>
              </div>

              <div className="space-y-1">
                <div className="text-slate-400 uppercase tracking-wider text-[10px] font-bold">Visa Letter Validity</div>
                <div className="flex items-center gap-1.5 font-semibold text-slate-800">
                  <Calendar className="w-3.5 h-3.5 text-slate-400" />
                  {activeCase.visaExpiry || 'Pending'}
                </div>
              </div>
            </div>
          </div>

          {/* FRRO Note */}
          <div className="bg-blue-50 border border-blue-100 rounded-2xl p-4 flex items-start gap-3 text-xs">
            <AlertCircle className="w-4 h-4 text-blue-500 shrink-0 mt-0.5" />
            <div className="text-blue-700">
              <strong>FRRO Registration:</strong> You will need to complete FRRO (Foreigner Regional Registration Office) registration within 14 days of arrival in India if your stay exceeds 180 days. Your hospital coordinator will assist with this process.
            </div>
          </div>
        </>
      )}
    </div>
  );
}
