"use client";

import React, { useState, useEffect } from "react";
import { 
  Plane, 
  FileText, 
  Download, 
  Building2, 
  MapPin, 
  Hotel, 
  CheckCircle2,
  Calendar,
  Phone,
  UserCheck,
  Check,
  AlertCircle,
  Loader2
} from "lucide-react";

export default function PatientTravelPage() {
  const [isDownloaded, setIsDownloaded] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [travelData, setTravelData] = useState<any>(null);

  useEffect(() => {
    const fetchTravelData = async () => {
      setIsLoading(true);
      try {
        const res = await fetch('/api/patient/travel');
        const data = await res.json();
        if (data.success) {
          setTravelData(data);
        }
      } catch (e) {
        console.error('Failed to load travel data', e);
      } finally {
        setIsLoading(false);
      }
    };
    fetchTravelData();
  }, []);

  const activeCase = travelData?.activeCase;
  const nextAppointment = travelData?.nextAppointment;

  const handleDownloadVisa = () => {
    setIsDownloaded(true);
    const refNo = activeCase?.visaReference || 'MED-VISA-PENDING';
    const hospital = activeCase?.hospital?.name || 'Your assigned hospital';
    const doctor = activeCase?.doctor?.name || 'Your assigned doctor';
    
    const content = `GOVERNMENT OF INDIA - EMBASSY VISA INVITATION SUPPORT
Ref No: ${refNo}

This is to certify that the named patient has been accepted for medical treatment (${activeCase?.treatment || 'Medical Treatment'}) at ${hospital} under the care of ${doctor}.

Validity: ${activeCase?.visaExpiry || 'As per visa stamp'}
Accreditation: Joint Commission International (JCI) Accredited Hospital.

Generated by MAIDES Medical Tourism Platform.`;
    
    const blob = new Blob([content], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `MAIDES-Visa-Letter-${refNo}.txt`;
    a.click();
    setTimeout(() => setIsDownloaded(false), 3000);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <Loader2 className="w-6 h-6 text-blue-600 animate-spin mr-2" />
        <span className="text-sm text-slate-500">Loading travel information...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div>
        <h1 className="text-xl font-bold text-slate-900 tracking-tight">
          Travel Itinerary & Medical Visa Hub
        </h1>
        <p className="text-xs text-slate-500 mt-1">
          Everything you need for your medical journey to Kerala: visa invitation letter, hospital details, and ground support.
        </p>
      </div>

      {!activeCase ? (
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 flex items-start gap-3 text-sm">
          <AlertCircle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-amber-800">No Active Medical Case</p>
            <p className="text-xs text-amber-600 mt-1">
              Your travel and visa information will appear here once your medical case has been approved and a hospital has been assigned. Please contact your coordinator if you need assistance.
            </p>
          </div>
        </div>
      ) : (
        <>
          {/* Visa Invitation Card */}
          <div className="bg-gradient-to-r from-blue-600 to-[#0F2042] text-white p-6 rounded-2xl shadow-md space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <span className="px-2.5 py-0.5 rounded-full bg-white/20 text-blue-100 text-xs font-semibold backdrop-blur-md">
                  {activeCase.visaStatus || 'Visa Status Pending'}
                </span>
                <h2 className="text-lg font-bold text-white mt-2">
                  Indian Medical Visa Support Document
                </h2>
                <p className="text-xs text-blue-100 mt-0.5">
                  Ref: {activeCase.visaReference || 'Pending'} • {activeCase.hospital?.name || 'Hospital TBA'}
                </p>
              </div>
              <button 
                onClick={handleDownloadVisa}
                className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white text-blue-900 hover:bg-blue-50 text-xs font-bold transition-all shadow shrink-0 cursor-pointer"
              >
                {isDownloaded ? <Check className="w-4 h-4 text-emerald-600" /> : <Download className="w-4 h-4 text-blue-600" />}
                {isDownloaded ? "Downloaded!" : "Download Visa Letter"}
              </button>
            </div>

            <div className="pt-3 border-t border-white/10 text-xs text-blue-100 grid grid-cols-1 sm:grid-cols-3 gap-2">
              <div>Treating Hospital: <strong className="text-white">{activeCase.hospital?.name || 'TBA'}</strong></div>
              <div>Physician: <strong className="text-white">{activeCase.doctor?.name || 'TBA'}</strong></div>
              <div>Visa Expiry: <strong className="text-white">{activeCase.visaExpiry || 'Pending'}</strong></div>
            </div>
          </div>

          {/* Active Case Details */}
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-blue-50 text-blue-600">
                <Building2 className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-sm font-bold text-slate-800">Hospital & Treatment Details</h2>
                <div className="text-xs text-slate-500">Your assigned treating hospital</div>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-slate-50 border border-slate-100 text-xs space-y-2">
              <div className="font-semibold text-slate-800 text-sm">{activeCase.hospital?.name || 'Pending Assignment'}</div>
              {activeCase.hospital?.city && (
                <div className="flex items-center gap-1.5 text-slate-600">
                  <MapPin className="w-3.5 h-3.5 text-blue-500" />
                  {activeCase.hospital.city}
                </div>
              )}
              {activeCase.hospital?.address && (
                <div className="text-slate-500">{activeCase.hospital.address}</div>
              )}
              {activeCase.hospital?.phone && (
                <a href={`tel:${activeCase.hospital.phone}`} className="text-blue-600 font-semibold flex items-center gap-1.5 hover:underline">
                  <Phone className="w-3.5 h-3.5" />
                  {activeCase.hospital.phone}
                </a>
              )}
              <div className="pt-1">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Treatment: </span>
                <span className="text-slate-700 font-semibold">{activeCase.treatment || 'Pending'}</span>
              </div>
            </div>
          </div>

          {/* Next Appointment */}
          {nextAppointment && (
            <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm">
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2 rounded-xl bg-emerald-50 text-emerald-600">
                  <Calendar className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-sm font-bold text-slate-800">Next Scheduled Appointment</h2>
                  <div className="text-xs text-slate-500">Confirmed in your medical calendar</div>
                </div>
              </div>
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-100 text-xs space-y-1.5">
                <div className="font-semibold text-slate-800 text-sm">
                  {new Date(nextAppointment.dateTime).toLocaleString('en-IN', {
                    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
                  })}
                </div>
                {nextAppointment.doctor?.name && (
                  <div className="text-slate-600">Physician: <strong className="text-slate-800">{nextAppointment.doctor.name}</strong></div>
                )}
                {nextAppointment.hospital?.name && (
                  <div className="text-slate-600">Location: <strong className="text-slate-800">{nextAppointment.hospital.name}</strong></div>
                )}
                <span className={`inline-flex px-2 py-0.5 rounded-full text-[10px] font-bold ${
                  nextAppointment.status === 'Confirmed' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'
                }`}>
                  {nextAppointment.status}
                </span>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
